### ISSUE TITLE
Command paths not appropriate for windows & require extension to be installed

### ISSUE THREAD

**Issue by danyill** [griffin-stewie/asciidoctor-preview#31]
The default paths require the asciidoctor-diagram package to be installed and don't function on a Windows platform.

I have removed this package dependency which should either be removed or noted in the documentation (`-r asciidoctor-diagram`) and quoted the paths in `command:default` as well as making the executable run `asciidoctor.bat`. I have also changed `path:default` to refer to the Ruby interpreter.

I can successfully run on Windows using the following:

```
module.exports =
  config:
    command:
      title: 'Command'
      description: 'You can use {{{tempHTMLPath}}}, {{{baseDirPath}}}, {{{filePath}}}'
      type: 'string'
      default: "asciidoctor.bat --safe-mode unsafe -a lang=ja -b html5 -d book --base-dir \"{{{baseDirPath}}}\" -o \"{{{tempHTMLPath}}}\" \"{{{filePath}}}\""
      order: 40
    path:
      title: 'PATH'
      description: 'for commands that you use'
      type: 'string'
      default: 'C:\\Ruby23\\bin\\'
      order: 41
```
